apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: gcr.io/google_containers/hyperkube:v1.1.4
    command:
    - /hyperkube
    - controller-manager
    - --master=http://127.0.0.1:<%= kube_master_port %>
    - --service-account-private-key-file=/etc/kubernetes/auth/auth_service_account.key
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 1
    volumeMounts:
    - mountPath: /etc/kubernetes/auth
      name: auth-config
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/auth
    name: auth-config
